import io
from PIL import Image, ImageDraw
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def generate_png(image_file, label, confidence):
    img = Image.open(image_file).convert("RGB")
    img = img.resize((500, 400))

    result_banner = Image.new("RGB", (500, 120), color=(238, 244, 231))
    draw = ImageDraw.Draw(result_banner)

    draw.text((20, 15), "🌿 PALAi — Detection Result", fill=(45, 80, 22))
    draw.text((20, 45), f"Category: {label}", fill=(30, 30, 30))
    draw.text((20, 70), f"Confidence: {confidence:.2f}%", fill=(90, 90, 84))

    bar_bg = (229, 229, 224)
    bar_fill = (61, 107, 30)
    draw.rectangle([20, 95, 480, 108], fill=bar_bg)
    draw.rectangle([20, 95, 20 + int(4.6 * confidence), 108], fill=bar_fill)

    combined = Image.new("RGB", (500, 520), color=(255, 255, 255))
    combined.paste(img, (0, 0))
    combined.paste(result_banner, (0, 400))

    buf = io.BytesIO()
    combined.save(buf, format="PNG")
    buf.seek(0)
    return buf


def generate_pdf(image_file, label, confidence):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter)
    width, height = letter

    # Header
    c.setFillColor(colors.HexColor("#2d5a1b"))
    c.rect(0, height - 60, width, 60, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, height - 38, "PALAi — Brown Spot Detection Report")

    # Result Section
    c.setFillColor(colors.HexColor("#1a1a16"))
    c.setFont("Helvetica-Bold", 13)
    c.drawString(40, height - 100, "Detection Result")

    c.setFont("Helvetica", 11)
    c.setFillColor(colors.HexColor("#5a5a54"))
    c.drawString(40, height - 125, f"Category:    {label}")
    c.drawString(40, height - 145, f"Confidence:  {confidence:.2f}% (how sure we are at Guessing this image)")

    # Confidence bar
    c.setFillColor(colors.HexColor("#e5e5e0"))
    c.rect(40, height - 170, 400, 10, fill=True, stroke=False)
    c.setFillColor(colors.HexColor("#3d6b1e"))
    c.rect(40, height - 170, int(4 * confidence), 10, fill=True, stroke=False)

    # Uploaded Image
    img = Image.open(image_file).convert("RGB")
    img_buf = io.BytesIO()
    img.save(img_buf, format="PNG")
    img_buf.seek(0)

    from reportlab.lib.utils import ImageReader
    c.drawImage(ImageReader(img_buf), 40, height - 420, width=300, height=220)

    # Footer
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#9ca3af"))
    c.drawString(40, 30, "Generated by PALAi · Brown Spot Detection System")

    c.save()
    buf.seek(0)
    return buf